version: '3.8'
services:
  postgresql:
    image: postgres
    environment:
      POSTGRES_DB: dockerDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
  
  springbootapp:
    image: springboot
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
